export const sampleData = {
  canadianCitizen: true,
  T5: {},
  foreignPropertyCheck: false,
  firstName: 'This is First',
  co: 'chad',
  areaCode: '+1',
  unit: '100',
  streetName: 'Some new Street',

  oldProvince: 'MB',
  sin: '999999999',
  outsideWhitehorse: false,
  netfileCode: '',
  indianAct: false,
  newImmigrantTax: false,
  lastName: 'Fern is the last',
  streetNo: '15801',
  maritalStatus: 4,
  fillingFirstTime: false,
  citizenOfSelfGoverning: false,
  prepareReturnsTogether: false,
  disposedPrincipalResidence: false,
  homeIsMailing: true,
  entryDate: '0805',
  selfGoverningNation: '',
  maritalStatusChanged: false,
  dob: '20220711',
  dod: '',
  postalCode: 'L11111',
  anyDependents: false,
  phoneNumber: '1231231721',
  prov: 'NB',
  id: 0,
  confinedToPrison: false,

  middleName: 'm',
  forDeceased: false,
  t5Forms: [],
  language: 'French',
  currentProvince: 'MB',
  city: 'toronto',
  resideInYukon: false,
  T4: {
    box10: 10,
    box14: 14,
    box16: 16,
    box17: 17,
    box18: 18,
    box20: 20,
    box22: 22,
    box22: 24,
    box26: 26,
    box29: 29,
    box42: 42,
    box44: 44,
    box46: 46,
    box50: 50,
    box52: 52,
    box55: 55,
    box56: 56,
    cpp: 'cpp',
    extraBoxes: 'extra boxes',
    employeeName: 'New Company',
  },
  businessProvince: 'NL',
  departureDate: '0805',
  email: '',
  rr: '',
  poBox: '',
  firstNameSpouse: '',
  sinSpouse: '',
  selfEmployedCheck: true,
  netIncomeSpouse: '',
  uccb11700: '',
  uccb21300: ''
}



